export const uiConfig = {
  panelColor: 0x1f2b20,
  textColor: '#fff4cf',
  onboarding: {
    x: 400,
    y: 150,
    width: 460,
    height: 36,
    textSize: '13px',
    objectiveAutoAdvanceMs: 1700,
  },
  status: {
    placementMessageMs: 2600,
    combatMessageMs: 1200,
  },
  shop: {
    panelX: 684,
    panelY: 64,
    panelWidth: 224,
    panelHeight: 116,
    titleY: 8,
    cardTitleFontSize: '14px',
    cardWidth: 64,
    cardHeight: 58,
    cardSpacingX: 70,
    cardPadding: 10,
    iconWidth: 18,
    iconHeight: 22,
    cardLabelFontSize: '12px',
    cardCostFontSize: '12px',
    minTouchablePx: 44,
  },
  hud: {
    topRowY: 12,
    topRowWidth: 540,
    topRowHeight: 38,
    topRowX: 280,
    bottomY: 450,
    bottomWidth: 760,
    bottomHeight: 56,
    selectedTextX: 28,
    statusTextX: 212,
    selectedFontSize: '12px',
    statusFontSize: '10px',
    previewFontSize: '10px',
    upgradeButtonWidth: 140,
    upgradeButtonHeight: 44,
    upgradeButtonX: 700,
    upgradeButtonY: 450,
    upgradeButtonFontSize: '12px',
    selectedLineY: 6,
    statusLineY: 24,
    previewLineY: 40,
    infoTextColor: '#c8d8b6',
    maxLevelText: 'MAX',
  },
} as const

export type UiConfig = typeof uiConfig
