export const uiConfig = {
  panelColor: 0x1f2b20,
  textColor: '#fff4cf',
  // What: Global UI dimensions shared across reusable components.
  // Feel: Keep all interactive controls at or above touch-target minimum.
  // Range: 44..140px for typical buttons.
  // Related: createSceneButton helpers and menu/options overlays.
  // Units: px (logical pixels).
  buttonDefaults: {
    minTouchablePx: 56,
    borderThickness: 1,
    defaultHeight: 56,
    normalFill: 0x3a5a3d,
    normalAlpha: 0.62,
    hoverFill: 0x5b7c4d,
    hoverAlpha: 0.8,
    pressedFill: 0x7b9f74,
    pressedAlpha: 1,
    disabledFill: 0x2c3a2d,
    disabledAlpha: 0.45,
  },
  mainMenu: {
    titleFontSize: '34px',
    subtitleFontSize: '18px',
    titleColor: '#fff3bf',
    subtitleColor: '#ffe5a8',
    panelY: 56,
    buttonY: 310,
    buttonSpacing: 220,
    backgroundTint: 0x000000,
    backgroundAlpha: 0.45,
    summaryOffsetY: 24,
  },
  onboarding: {
    x: 400,
    y: 152,
    width: 500,
    height: 48,
    textSize: '14px',
    objectiveAutoAdvanceMs: 1700,
  },
  status: {
    placementMessageMs: 2600,
    combatMessageMs: 1200,
    criticalMessageMs: 3000,
    changeFeedbackMs: 900,
    sellConfirmMs: 2400,
  },
  audioPanel: {
    width: 640,
    height: 280,
    titleFontSize: '22px',
    labelFontSize: '16px',
    valueFontSize: '13px',
    valueColor: '#ffe6a8',
    panelColor: 0x1f2b20,
    trackHeight: 16,
    trackColor: 0x22331a,
    fillColor: 0x70aa58,
    thumbSize: 28,
    thumbColor: 0x9fd07b,
    marginX: 32,
    marginY: 18,
    closeButtonWidth: 118,
    closeButtonHeight: 44,
    closeButtonFontSize: '14px',
  },
  pauseMenu: {
    // What: Placement and size of the in-game pause control and overlays.
    // Feel: Reachable on touch without covering the shop or bottom HUD.
    // Range: Controls >=44px; overlay depth above gameplay HUD.
    // Related: PauseMenuController and shared AudioSettingsPanel.
    // Units: px (logical pixels), except colors/depth.
    buttonX: 568,
    buttonY: 30,
    buttonSize: 56,
    panelWidth: 340,
    panelHeight: 320,
    panelColor: 0x1f2b20,
    depth: 180,
    buttonWidth: 210,
    confirmPanelWidth: 420,
    confirmPanelHeight: 180,
    confirmButtonWidth: 130,
    audioDepthOffset: 50,
  },
  // What: Portrait-only device rotation gate and supported compact landscape floor.
  // Feel: Unmissable and calm; it fully replaces game interaction until rotation.
  // Range: Depth above all overlays; landscape floor 667x375 CSS pixels.
  // Related: PortraitOrientationGate and the fixed 800x480 logical canvas.
  // Units: CSS px for viewport minimums, logical px for visuals.
  orientationGate: {
    minimumLandscapeWidth: 667,
    minimumLandscapeHeight: 375,
    depth: 1000,
    backgroundColor: 0x111812,
    backgroundAlpha: 1,
    panelColor: 0x1f2b20,
    panelAlpha: 1,
    panelWidth: 420,
    panelHeight: 300,
    panelStrokeWidth: 2,
    deviceWidth: 104,
    deviceHeight: 164,
    deviceStrokeWidth: 4,
    deviceOffsetY: -34,
    arrowOffsetX: 94,
    arrowFontSize: '52px',
    titleOffsetY: 78,
    bodyOffsetY: 112,
    bodyWrapWidth: 340,
    titleFontSize: '28px',
    bodyFontSize: '16px',
    title: 'Rotate your device',
    instructions: 'Hidden Dojo Defense plays in landscape.',
  },
  shop: {
    panelX: 696,
    panelY: 68,
    panelWidth: 200,
    panelHeight: 124,
    titleY: 8,
    cardTitleFontSize: '14px',
    cardWidth: 56,
    cardHeight: 64,
    cardSpacingX: 62,
    cardPadding: 7,
    iconWidth: 18,
    iconHeight: 22,
    cardLabelFontSize: '11px',
    cardCostFontSize: '11px',
    minTouchablePx: 56,
  },
  hud: {
    topRowY: 2,
    topRowWidth: 592,
    topRowHeight: 56,
    topRowX: 296,
    bottomY: 442,
    bottomWidth: 784,
    bottomHeight: 72,
    selectedTextX: 28,
    statusTextX: 212,
    selectedFontSize: '13px',
    statusFontSize: '12px',
    previewFontSize: '11px',
    upgradeButtonWidth: 140,
    upgradeButtonHeight: 56,
    upgradeButtonX: 708,
    upgradeButtonY: 442,
    upgradeButtonFontSize: '13px',
    selectedLineY: 7,
    statusLineY: 29,
    previewLineY: 49,
    infoTextColor: '#c8d8b6',
    maxLevelText: 'MAX',
  },
} as const

export type UiConfig = typeof uiConfig
