export const uiConfig = {
  panelColor: 0x1f2b20,
  textColor: '#fff4cf',
  // What: Global UI dimensions shared across reusable components.
  // Feel: Keep all interactive controls at or above touch-target minimum.
  // Range: 44..140px for typical buttons.
  // Related: createSceneButton helpers and menu/options overlays.
  // Units: px (logical pixels).
  buttonDefaults: {
    minTouchablePx: 44,
    borderThickness: 1,
    defaultHeight: 48,
    normalFill: 0x3a5a3d,
    normalAlpha: 0.62,
    hoverFill: 0x5b7c4d,
    hoverAlpha: 0.8,
    pressedFill: 0x7b9f74,
    pressedAlpha: 1,
    disabledFill: 0x2c3a2d,
    disabledAlpha: 0.45,
  },
  mainMenu: {
    titleFontSize: '34px',
    subtitleFontSize: '18px',
    titleColor: '#fff3bf',
    subtitleColor: '#ffe5a8',
    panelY: 56,
    buttonY: 310,
    buttonSpacing: 220,
    backgroundTint: 0x000000,
    backgroundAlpha: 0.45,
    summaryOffsetY: 24,
  },
  onboarding: {
    x: 400,
    y: 150,
    width: 460,
    height: 36,
    textSize: '13px',
    objectiveAutoAdvanceMs: 1700,
  },
  status: {
    placementMessageMs: 2600,
    combatMessageMs: 1200,
  },
  audioPanel: {
    width: 640,
    height: 280,
    titleFontSize: '22px',
    labelFontSize: '16px',
    valueFontSize: '13px',
    valueColor: '#ffe6a8',
    panelColor: 0x1f2b20,
    trackHeight: 16,
    trackColor: 0x22331a,
    fillColor: 0x70aa58,
    thumbSize: 28,
    thumbColor: 0x9fd07b,
    marginX: 32,
    marginY: 18,
    closeButtonWidth: 118,
    closeButtonHeight: 44,
    closeButtonFontSize: '14px',
  },
  pauseMenu: {
    // What: Placement and size of the in-game pause control and overlays.
    // Feel: Reachable on touch without covering the shop or bottom HUD.
    // Range: Controls >=44px; overlay depth above gameplay HUD.
    // Related: PauseMenuController and shared AudioSettingsPanel.
    // Units: px (logical pixels), except colors/depth.
    buttonX: 772,
    buttonY: 150,
    buttonSize: 48,
    panelWidth: 340,
    panelHeight: 320,
    panelColor: 0x1f2b20,
    depth: 180,
    buttonWidth: 210,
    confirmPanelWidth: 420,
    confirmPanelHeight: 180,
    confirmButtonWidth: 130,
    audioDepthOffset: 50,
  },
  shop: {
    panelX: 684,
    panelY: 64,
    panelWidth: 224,
    panelHeight: 116,
    titleY: 8,
    cardTitleFontSize: '14px',
    cardWidth: 64,
    cardHeight: 58,
    cardSpacingX: 70,
    cardPadding: 10,
    iconWidth: 18,
    iconHeight: 22,
    cardLabelFontSize: '12px',
    cardCostFontSize: '12px',
    minTouchablePx: 44,
  },
  hud: {
    topRowY: 12,
    topRowWidth: 540,
    topRowHeight: 38,
    topRowX: 280,
    bottomY: 450,
    bottomWidth: 760,
    bottomHeight: 56,
    selectedTextX: 28,
    statusTextX: 212,
    selectedFontSize: '12px',
    statusFontSize: '10px',
    previewFontSize: '10px',
    upgradeButtonWidth: 140,
    upgradeButtonHeight: 44,
    upgradeButtonX: 700,
    upgradeButtonY: 450,
    upgradeButtonFontSize: '12px',
    selectedLineY: 6,
    statusLineY: 24,
    previewLineY: 40,
    infoTextColor: '#c8d8b6',
    maxLevelText: 'MAX',
  },
} as const

export type UiConfig = typeof uiConfig
